### PR TITLE
Refactor app swap changing cname

### PR DESCRIPTION
**Pull request by mportela**
Change the deploy_swap behavior, removing logic with cname-remove + add-cname in favor of tsuru command swap cname-only.

Also refactor the swap method to accept the parameter `force`, and when used in the new deploy_swap method this will only be considered valid if the previous step, add_units works as expected...

### CODE REVIEW

**Comment by vsouza** [comment]
good catch! It seems nice and smooth evolution.

**Comment by emerleite** [comment]
@vsouza @bernardolins @mportela should we merge this?

**Comment by mportela** [comment]
> @vsouza @bernardolins @mportela should we merge this?

to test, I have already run locally in a real situation of blue/green app swap, and it works

**Comment by vsouza** [comment]
Sounds good to me

**Comment by emerleite** [comment]
Bumped version 1.4.3

**Pull request merged**
