### PR TITLE
Add support for multiple files on deploy_dir option

### PR DESCRIPTION
**Pull request by aitherios**

### CODE REVIEW

**Comment by emerleite** [comment]
LGTM. Will integrate this weekend

**Comment by aitherios** [comment]
💃  let's do this 😄

**Comment by emerleite** [comment]
@aitherios Now :)

**Comment by emerleite** [comment]
@aitherios `tsuru plugin-install bluegreen https://raw.githubusercontent.com/emerleite/tsuru-bluegreen/1.3.0/src/bluegreen.py`

**Pull request merged**
